/*! Video.js v4.1.0 Copyright 2013 Brightcove, Inc. https://github.com/videojs/video.js/blob/master/LICENSE */
 (function() {var b=void 0,f=!0,h=null,l=!1;function m(){return function(){}}function p(a){return function(){return this[a]}}function r(a){return function(){return a}}var t;document.createElement("video");document.createElement("audio");document.createElement("track");function u(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.wa[a])return u.wa[a];a=u.r(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new u.D(a,c,d)}var v=u;
window.Bd=window.Cd=u;u.Qb="4.1";u.yc="https:"==document.location.protocol?"https://":"http://";u.options={techOrder:["html5","flash"],html5:{},flash:{},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};"GENERATED_CDN_VSN"!==u.Qb&&(v.options.flash.swf=u.yc+"vjs.zencdn.net/"+u.Qb+"/video-js.swf");u.wa={};u.la=u.CoreObject=m();
u.la.extend=function(a){var c,d;a=a||{};c=a.init||a.g||this.prototype.init||this.prototype.g||m();d=function(){c.apply(this,arguments)};d.prototype=u.i.create(this.prototype);d.prototype.constructor=d;d.extend=u.la.extend;d.create=u.la.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};u.la.create=function(){var a=u.i.create(this.prototype);this.apply(a,arguments);return a};
u.d=function(a,c,d){var e=u.getData(a);e.z||(e.z={});e.z[c]||(e.z[c]=[]);d.u||(d.u=u.u++);e.z[c].push(d);e.U||(e.disabled=l,e.U=function(c){if(!e.disabled){c=u.gc(c);var d=e.z[c.type];if(d)for(var d=d.slice(0),k=0,q=d.length;k<q&&!c.mc();k++)d[k].call(a,c)}});1==e.z[c].length&&(document.addEventListener?a.addEventListener(c,e.U,l):document.attachEvent&&a.attachEvent("on"+c,e.U))};
u.s=function(a,c,d){if(u.lc(a)){var e=u.getData(a);if(e.z)if(c){var g=e.z[c];if(g){if(d){if(d.u)for(e=0;e<g.length;e++)g[e].u===d.u&&g.splice(e--,1)}else e.z[c]=[];u.dc(a,c)}}else for(g in e.z)c=g,e.z[c]=[],u.dc(a,c)}};u.dc=function(a,c){var d=u.getData(a);0===d.z[c].length&&(delete d.z[c],document.removeEventListener?a.removeEventListener(c,d.U,l):document.detachEvent&&a.detachEvent("on"+c,d.U));u.Bb(d.z)&&(delete d.z,delete d.U,delete d.disabled);u.Bb(d)&&u.sc(a)};
u.gc=function(a){function c(){return f}function d(){return l}if(!a||!a.Cb){var e=a||window.event;a={};for(var g in e)"layerX"!==g&&"layerY"!==g&&(a[g]=e[g]);a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=l;a.Ab=c};a.Ab=d;a.stopPropagation=function(){e.stopPropagation&&e.stopPropagation();a.cancelBubble=f;a.Cb=c};a.Cb=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&
e.stopImmediatePropagation();a.mc=c;a.stopPropagation()};a.mc=d;if(a.clientX!=h){g=document.documentElement;var j=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||j&&j.scrollLeft||0)-(g&&g.clientLeft||j&&j.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||j&&j.scrollTop||0)-(g&&g.clientTop||j&&j.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.j=function(a,c){var d=u.lc(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=u.gc(c);d.U&&d.U.call(a,c);if(e&&!c.Cb())u.j(e,c);else if(!e&&!c.Ab()&&(d=u.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=l}return!c.Ab()};u.S=function(a,c,d){u.d(a,c,function(){u.s(a,c,arguments.callee);d.apply(this,arguments)})};var w=Object.prototype.hasOwnProperty;
u.e=function(a,c){var d=document.createElement(a||"div"),e;for(e in c)w.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};u.$=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.i={};u.i.create=Object.create||function(a){function c(){}c.prototype=a;return new c};u.i.sa=function(a,c,d){for(var e in a)w.call(a,e)&&c.call(d||this,e,a[e])};u.i.B=function(a,c){if(!c)return a;for(var d in c)w.call(c,d)&&(a[d]=c[d]);return a};
u.i.fc=function(a,c){var d,e,g;a=u.i.copy(a);for(d in c)w.call(c,d)&&(e=a[d],g=c[d],a[d]=u.i.nc(e)&&u.i.nc(g)?u.i.fc(e,g):c[d]);return a};u.i.copy=function(a){return u.i.B({},a)};u.i.nc=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};u.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.u||(c.u=u.u++);e.u=d?d+"_"+c.u:c.u;return e};u.qa={};u.u=1;u.expando="vdata"+(new Date).getTime();
u.getData=function(a){var c=a[u.expando];c||(c=a[u.expando]=u.u++,u.qa[c]={});return u.qa[c]};u.lc=function(a){a=a[u.expando];return!(!a||u.Bb(u.qa[a]))};u.sc=function(a){var c=a[u.expando];if(c){delete u.qa[c];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};u.Bb=function(a){for(var c in a)if(a[c]!==h)return l;return f};u.p=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};
u.w=function(a,c){if(-1!=a.className.indexOf(c)){for(var d=a.className.split(" "),e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};u.na=u.e("video");u.H=navigator.userAgent;u.Cc=/iPhone/i.test(u.H);u.Bc=/iPad/i.test(u.H);u.Dc=/iPod/i.test(u.H);u.Tb=u.Cc||u.Bc||u.Dc;var aa=u,x;var y=u.H.match(/OS (\d+)_/i);x=y&&y[1]?y[1]:b;aa.sd=x;u.bb=/Android/i.test(u.H);var ba=u,z;var A=u.H.match(/Android (\d+)(?:\.(\d+))?(?:\.(\d+))*/i),B,C;
A?(B=A[1]&&parseFloat(A[1]),C=A[2]&&parseFloat(A[2]),z=B&&C?parseFloat(A[1]+"."+A[2]):B?B:h):z=h;ba.zc=z;u.Ec=u.bb&&/webkit/i.test(u.H)&&2.3>u.zc;u.Ac=/Firefox/i.test(u.H);u.td=/Chrome/i.test(u.H);u.xb=function(a){var c={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,j=d.length-1;0<=j;j--){e=d[j].name;g=d[j].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:l;c[e]=g}return c};
u.xd=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};u.zb=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};u.Ob={};u.r=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.La=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),j=Math.floor(c/60%60),k=Math.floor(c/3600),g=0<g||0<k?g+":":"";return g+(((g||10<=j)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.Ic=function(){document.body.focus();document.onselectstart=r(l)};u.nd=function(){document.onselectstart=r(f)};u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};
u.tb=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
u.get=function(a,c,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(j){d(j)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?c(g.responseText):d&&d())};try{g.send()}catch(k){d&&d(k)}};u.fd=function(a){try{var c=window.localStorage||l;c&&(c.volume=a)}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):18==d.code?u.log("LocalStorage not allowed (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.jc=function(a){a.match(/^https?:\/\//)||(a=u.e("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Qc=function(a){var c,d;a.getBoundingClientRect&&a.parentNode&&(c=a.getBoundingClientRect());if(!c)return{left:0,top:0};a=document.documentElement;d=document.body;return{left:c.left+(window.pageXOffset||d.scrollLeft)-(a.clientLeft||d.clientLeft||0),top:c.top+(window.pageYOffset||d.scrollTop)-(a.clientTop||d.clientTop||0)}};
u.c=u.la.extend({g:function(a,c,d){this.a=a;this.f=u.i.copy(this.f);c=this.options(c);this.P=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+u.u++);this.Vc=c.name||h;this.b=c.el||this.e();this.I=[];this.sb={};this.T={};if((a=this.f)&&a.children){var e=this;u.i.sa(a.children,function(a,c){c!==l&&!c.loadEvent&&(e[a]=e.Z(a,c))})}this.Q(d)}});t=u.c.prototype;
t.F=function(){this.j("dispose");if(this.I)for(var a=this.I.length-1;0<=a;a--)this.I[a].F&&this.I[a].F();this.T=this.sb=this.I=h;this.s();this.b.parentNode&&this.b.parentNode.removeChild(this.b);u.sc(this.b);this.b=h};t.pc=p("a");t.options=function(a){return a===b?this.f:this.f=u.i.fc(this.f,a)};t.e=function(a,c){return u.e(a,c)};t.r=p("b");t.id=p("P");t.name=p("Vc");t.children=p("I");
t.Z=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||u.$(e),c.name=e,d=new window.videojs[d](this.a||this,c)):d=a;this.I.push(d);"function"===typeof d.id&&(this.sb[d.id()]=d);(e=e||d.name&&d.name())&&(this.T[e]=d);"function"===typeof d.el&&d.el()&&(this.ra||this.b).appendChild(d.el());return d};
t.removeChild=function(a){"string"===typeof a&&(a=this.T[a]);if(a&&this.I){for(var c=l,d=this.I.length-1;0<=d;d--)if(this.I[d]===a){c=f;this.I.splice(d,1);break}c&&(this.sb[a.id]=h,this.T[a.name]=h,(c=a.r())&&c.parentNode===(this.ra||this.b)&&(this.ra||this.b).removeChild(a.r()))}};t.R=r("");t.d=function(a,c){u.d(this.b,a,u.bind(this,c));return this};t.s=function(a,c){u.s(this.b,a,c);return this};t.S=function(a,c){u.S(this.b,a,u.bind(this,c));return this};t.j=function(a,c){u.j(this.b,a,c);return this};
t.Q=function(a){a&&(this.ba?a.call(this):(this.Sa===b&&(this.Sa=[]),this.Sa.push(a)));return this};t.Ua=function(){this.ba=f;var a=this.Sa;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.Sa=[];this.j("ready")}};t.p=function(a){u.p(this.b,a);return this};t.w=function(a){u.w(this.b,a);return this};t.show=function(){this.b.style.display="block";return this};t.v=function(){this.b.style.display="none";return this};t.aa=function(){this.w("vjs-fade-out");this.p("vjs-fade-in");return this};
t.ua=function(){this.w("vjs-fade-in");this.p("vjs-fade-out");return this};t.oc=function(){this.p("vjs-lock-showing");return this};t.Va=function(){this.w("vjs-lock-showing");return this};t.disable=function(){this.v();this.show=m();this.aa=m()};t.width=function(a,c){return D(this,"width",a,c)};t.height=function(a,c){return D(this,"height",a,c)};t.Mc=function(a,c){return this.width(a,f).height(c)};
function D(a,c,d,e){if(d!==b)return a.b.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.j("resize"),a;if(!a.b)return 0;d=a.b.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.b["offset"+u.$(c)],10)}
u.o=u.c.extend({g:function(a,c){u.c.call(this,a,c);var d=l;this.d("touchstart",function(){d=f});this.d("touchmove",function(){d=l});var e=this;this.d("touchend",function(a){d&&e.n(a);a.preventDefault();a.stopPropagation()});this.d("click",this.n);this.d("focus",this.Oa);this.d("blur",this.Na)}});t=u.o.prototype;
t.e=function(a,c){c=u.i.B({className:this.R(),innerHTML:'<div class="vjs-control-content"><span class="vjs-control-text">'+(this.pa||"Need Text")+"</span></div>",cd:"button","aria-live":"polite",tabIndex:0},c);return u.c.prototype.e.call(this,a,c)};t.R=function(){return"vjs-control "+u.c.prototype.R.call(this)};t.n=m();t.Oa=function(){u.d(document,"keyup",u.bind(this,this.ca))};t.ca=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.n()};
t.Na=function(){u.s(document,"keyup",u.bind(this,this.ca))};u.N=u.c.extend({g:function(a,c){u.c.call(this,a,c);this.Hc=this.T[this.f.barName];this.handle=this.T[this.f.handleName];a.d(this.qc,u.bind(this,this.update));this.d("mousedown",this.Pa);this.d("touchstart",this.Pa);this.d("focus",this.Oa);this.d("blur",this.Na);this.d("click",this.n);this.a.d("controlsvisible",u.bind(this,this.update));a.Q(u.bind(this,this.update));this.O={}}});t=u.N.prototype;
t.e=function(a,c){c=c||{};c.className+=" vjs-slider";c=u.i.B({cd:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},c);return u.c.prototype.e.call(this,a,c)};t.Pa=function(a){a.preventDefault();u.Ic();this.O.move=u.bind(this,this.Hb);this.O.end=u.bind(this,this.Ib);u.d(document,"mousemove",this.O.move);u.d(document,"mouseup",this.O.end);u.d(document,"touchmove",this.O.move);u.d(document,"touchend",this.O.end);this.Hb(a)};
t.Ib=function(){u.nd();u.s(document,"mousemove",this.O.move,l);u.s(document,"mouseup",this.O.end,l);u.s(document,"touchmove",this.O.move,l);u.s(document,"touchend",this.O.end,l);this.update()};t.update=function(){if(this.b){var a,c=this.yb(),d=this.handle,e=this.Hc;isNaN(c)&&(c=0);a=c;if(d){a=this.b.offsetWidth;var g=d.r().offsetWidth;a=g?g/a:0;c*=1-a;a=c+a/2;d.r().style.left=u.round(100*c,2)+"%"}e.r().style.width=u.round(100*a,2)+"%"}};
function E(a,c){var d,e,g,j;d=a.b;e=u.Qc(d);j=g=d.offsetWidth;d=a.handle;if(a.f.od)return j=e.top,e=c.changedTouches?c.changedTouches[0].pageY:c.pageY,d&&(d=d.r().offsetHeight,j+=d/2,g-=d),Math.max(0,Math.min(1,(j-e+g)/g));g=e.left;e=c.changedTouches?c.changedTouches[0].pageX:c.pageX;d&&(d=d.r().offsetWidth,g+=d/2,j-=d);return Math.max(0,Math.min(1,(e-g)/j))}t.Oa=function(){u.d(document,"keyup",u.bind(this,this.ca))};
t.ca=function(a){37==a.which?(a.preventDefault(),this.vc()):39==a.which&&(a.preventDefault(),this.wc())};t.Na=function(){u.s(document,"keyup",u.bind(this,this.ca))};t.n=function(a){a.stopImmediatePropagation();a.preventDefault()};u.ha=u.c.extend();u.ha.prototype.defaultValue=0;u.ha.prototype.e=function(a,c){c=c||{};c.className+=" vjs-slider-handle";c=u.i.B({innerHTML:'<span class="vjs-control-text">'+this.defaultValue+"</span>"},c);return u.c.prototype.e.call(this,"div",c)};u.ma=u.c.extend();
function ca(a,c){a.Z(c);c.d("click",u.bind(a,function(){this.Va()}))}u.ma.prototype.e=function(){var a=this.options().Kc||"ul";this.ra=u.e(a,{className:"vjs-menu-content"});a=u.c.prototype.e.call(this,"div",{append:this.ra,className:"vjs-menu"});a.appendChild(this.ra);u.d(a,"click",function(a){a.preventDefault();a.stopImmediatePropagation()});return a};u.M=u.o.extend({g:function(a,c){u.o.call(this,a,c);this.selected(c.selected)}});
u.M.prototype.e=function(a,c){return u.o.prototype.e.call(this,"li",u.i.B({className:"vjs-menu-item",innerHTML:this.f.label},c))};u.M.prototype.n=function(){this.selected(f)};u.M.prototype.selected=function(a){a?(this.p("vjs-selected"),this.b.setAttribute("aria-selected",f)):(this.w("vjs-selected"),this.b.setAttribute("aria-selected",l))};
u.C=u.o.extend({g:function(a,c){u.o.call(this,a,c);this.va=this.Ka();this.Z(this.va);this.K&&0===this.K.length&&this.v();this.d("keyup",this.ca);this.b.setAttribute("aria-haspopup",f);this.b.setAttribute("role","button")}});u.C.prototype.oa=l;u.C.prototype.Ka=function(){var a=new u.ma(this.a);this.options().title&&a.r().appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.$(this.A),ld:-1}));if(this.K=this.createItems())for(var c=0;c<this.K.length;c++)ca(a,this.K[c]);return a};
u.C.prototype.createItems=m();t=u.C.prototype;t.R=function(){return this.className+" vjs-menu-button "+u.o.prototype.R.call(this)};t.Oa=m();t.Na=m();t.n=function(){this.S("mouseout",u.bind(this,function(){this.va.Va();this.b.blur()}));this.oa?F(this):G(this)};t.ca=function(a){a.preventDefault();32==a.which||13==a.which?this.oa?F(this):G(this):27==a.which&&this.oa&&F(this)};function G(a){a.oa=f;a.va.oc();a.b.setAttribute("aria-pressed",f);a.K&&0<a.K.length&&a.K[0].r().focus()}
function F(a){a.oa=l;a.va.Va();a.b.setAttribute("aria-pressed",l)}
u.D=u.c.extend({g:function(a,c,d){this.G=a;c=u.i.B(da(a),c);this.t={};this.rc=c.poster;this.Ja=c.controls;c.customControlsOnMobile!==f&&(u.Tb||u.bb)?(a.controls=c.controls,this.Ja=l):a.controls=l;u.c.call(this,this,c,d);this.S("play",function(a){u.j(this.b,{type:"firstplay",target:this.b})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.d("ended",this.Xc);this.d("play",this.Kb);this.d("firstplay",this.Yc);this.d("pause",this.Jb);this.d("progress",this.$c);this.d("durationchange",
this.Wc);this.d("error",this.Gb);this.d("fullscreenchange",this.Zc);u.wa[this.P]=this;c.plugins&&u.i.sa(c.plugins,function(a,c){this[a](c)},this)}});t=u.D.prototype;t.f=u.options;t.F=function(){this.j("dispose");this.s("dispose");u.wa[this.P]=h;this.G&&this.G.player&&(this.G.player=h);this.b&&this.b.player&&(this.b.player=h);clearInterval(this.Ra);this.ya();this.h&&this.h.F();u.c.prototype.F.call(this)};
function da(a){var c={sources:[],tracks:[]};u.i.B(c,u.xb(a));if(a.hasChildNodes()){var d,e,g,j;a=a.childNodes;g=0;for(j=a.length;g<j;g++)d=a[g],e=d.nodeName.toLowerCase(),"source"===e?c.sources.push(u.xb(d)):"track"===e&&c.tracks.push(u.xb(d))}return c}
t.e=function(){var a=this.b=u.c.prototype.e.call(this,"div"),c=this.G;c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes()){var d,e,g,j,k;d=c.childNodes;e=d.length;for(k=[];e--;)g=d[e],j=g.nodeName.toLowerCase(),("source"===j||"track"===j)&&k.push(g);for(d=0;d<k.length;d++)c.removeChild(k[d])}c.id=c.id||"vjs_video_"+u.u++;a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.p("vjs-paused");this.width(this.f.width,f);this.height(this.f.height,
f);c.parentNode&&c.parentNode.insertBefore(a,c);u.zb(c,a);return a};
function H(a,c,d){a.h?(a.ba=l,a.h.F(),a.Eb&&(a.Eb=l,clearInterval(a.Ra)),a.Fb&&I(a),a.h=l):"Html5"!==c&&a.G&&(a.b.removeChild(a.G),a.G.player=h,a.G=h);a.za=c;a.ba=l;var e=u.i.B({source:d,parentEl:a.b},a.f[c.toLowerCase()]);d&&(d.src==a.t.src&&0<a.t.currentTime&&(e.startTime=a.t.currentTime),a.t.src=d.src);a.h=new window.videojs[c](a,e);a.h.Q(function(){this.a.Ua();if(!this.k.Mb){var a=this.a;a.Eb=f;a.Ra=setInterval(u.bind(a,function(){this.t.nb<this.buffered().end(0)?this.j("progress"):1==this.Ia()&&
(clearInterval(this.Ra),this.j("progress"))}),500);a.h.S("progress",function(){this.k.Mb=f;var a=this.a;a.Eb=l;clearInterval(a.Ra)})}this.k.Pb||(a=this.a,a.Fb=f,a.d("play",a.xc),a.d("pause",a.ya),a.h.S("timeupdate",function(){this.k.Pb=f;I(this.a)}))})}function I(a){a.Fb=l;a.ya();a.s("play",a.xc);a.s("pause",a.ya)}t.xc=function(){this.ec&&this.ya();this.ec=setInterval(u.bind(this,function(){this.j("timeupdate")}),250)};t.ya=function(){clearInterval(this.ec)};
t.Xc=function(){this.f.loop&&(this.currentTime(0),this.play())};t.Kb=function(){u.w(this.b,"vjs-paused");u.p(this.b,"vjs-playing")};t.Yc=function(){this.f.starttime&&this.currentTime(this.f.starttime)};t.Jb=function(){u.w(this.b,"vjs-playing");u.p(this.b,"vjs-paused")};t.$c=function(){1==this.Ia()&&this.j("loadedalldata")};t.Wc=function(){this.duration(J(this,"duration"))};t.Gb=function(a){u.log("Video Error",a)};t.Zc=function(){this.J?this.p("vjs-fullscreen"):this.w("vjs-fullscreen")};
function K(a,c,d){if(a.h&&!a.h.ba)a.h.Q(function(){this[c](d)});else try{a.h[c](d)}catch(e){throw u.log(e),e;}}function J(a,c){if(a.h.ba)try{return a.h[c]()}catch(d){throw a.h[c]===b?u.log("Video.js: "+c+" method not defined for "+a.za+" playback technology.",d):"TypeError"==d.name?(u.log("Video.js: "+c+" unavailable on "+a.za+" playback technology element.",d),a.h.ba=l):u.log(d),d;}}t.play=function(){K(this,"play");return this};t.pause=function(){K(this,"pause");return this};
t.paused=function(){return J(this,"paused")===l?l:f};t.currentTime=function(a){return a!==b?(this.t.zd=a,K(this,"setCurrentTime",a),this.Fb&&this.j("timeupdate"),this):this.t.currentTime=J(this,"currentTime")||0};t.duration=function(a){return a!==b?(this.t.duration=parseFloat(a),this):this.t.duration};t.buffered=function(){var a=J(this,"buffered"),c=this.t.nb=this.t.nb||0;a&&(0<a.length&&a.end(0)!==c)&&(c=a.end(0),this.t.nb=c);return u.tb(0,c)};
t.Ia=function(){return this.duration()?this.buffered().end(0)/this.duration():0};t.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.t.volume=a,K(this,"setVolume",a),u.fd(a),this;a=parseFloat(J(this,"volume"));return isNaN(a)?1:a};t.muted=function(a){return a!==b?(K(this,"setMuted",a),this):J(this,"muted")||l};t.Ta=function(){return J(this,"supportsFullScreen")||l};
t.xa=function(){var a=u.Ob.xa;this.J=f;a?(u.d(document,a.vb,u.bind(this,function(c){this.J=document[a.J];this.J===l&&u.s(document,a.vb,arguments.callee);this.j("fullscreenchange")})),this.b[a.tc]()):this.h.Ta()?K(this,"enterFullScreen"):(this.Sc=f,this.Nc=document.documentElement.style.overflow,u.d(document,"keydown",u.bind(this,this.hc)),document.documentElement.style.overflow="hidden",u.p(document.body,"vjs-full-window"),this.j("enterFullWindow"),this.j("fullscreenchange"));return this};
t.qb=function(){var a=u.Ob.xa;this.J=l;if(a)document[a.pb]();else this.h.Ta()?K(this,"exitFullScreen"):(L(this),this.j("fullscreenchange"));return this};t.hc=function(a){27===a.keyCode&&(this.J===f?this.qb():L(this))};function L(a){a.Sc=l;u.s(document,"keydown",a.hc);document.documentElement.style.overflow=a.Nc;u.w(document.body,"vjs-full-window");a.j("exitFullWindow")}
t.src=function(a){if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.f.techOrder;d<e.length;d++){var g=u.$(e[d]),j=window.videojs[g];if(j.isSupported())for(var k=0,q=c;k<q.length;k++){var n=q[k];if(j.canPlaySource(n)){c={source:n,h:g};break a}}}c=l}c?(a=c.source,c=c.h,c==this.za?this.src(a):H(this,c,a)):this.b.appendChild(u.e("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.za].canPlaySource(a)?this.src(a.src):this.src([a]):(this.t.src=a,this.ba?(K(this,"src",a),"auto"==this.f.preload&&this.load(),this.f.autoplay&&this.play()):this.Q(function(){this.src(a)}));return this};t.load=function(){K(this,"load");return this};t.currentSrc=function(){return J(this,"currentSrc")||this.t.src||""};t.Qa=function(a){return a!==b?(K(this,"setPreload",a),this.f.preload=a,this):J(this,"preload")};
t.autoplay=function(a){return a!==b?(K(this,"setAutoplay",a),this.f.autoplay=a,this):J(this,"autoplay")};t.loop=function(a){return a!==b?(K(this,"setLoop",a),this.f.loop=a,this):J(this,"loop")};t.poster=function(a){a!==b&&(this.rc=a);return this.rc};t.controls=function(a){a!==b&&this.Ja!==a&&(this.Ja=!!a,this.j("controlschange"));return this.Ja};t.error=function(){return J(this,"error")};var M,N,O;O=document.createElement("div");N={};
O.ud!==b?(N.tc="requestFullscreen",N.pb="exitFullscreen",N.vb="fullscreenchange",N.J="fullScreen"):(document.mozCancelFullScreen?(M="moz",N.J=M+"FullScreen"):(M="webkit",N.J=M+"IsFullScreen"),O[M+"RequestFullScreen"]&&(N.tc=M+"RequestFullScreen",N.pb=M+"CancelFullScreen"),N.vb=M+"fullscreenchange");document[N.pb]&&(u.Ob.xa=N);
u.fa=u.c.extend({g:function(a,c){u.c.call(this,a,c);a.controls()||this.disable();a.S("play",u.bind(this,function(){var a,c=u.bind(this,this.aa),g=u.bind(this,this.ua);this.aa();"ontouchstart"in window||(this.a.d("mouseover",c),this.a.d("mouseout",g),this.a.d("pause",u.bind(this,this.oc)),this.a.d("play",u.bind(this,this.Va)));a=l;this.a.d("touchstart",function(){a=f});this.a.d("touchmove",function(){a=l});this.a.d("touchend",u.bind(this,function(c){var e;a&&(e=this.r().className.search("fade-in"),
-1!==e?this.ua():this.aa());a=l;this.a.paused()||c.preventDefault()}))}))}});u.fa.prototype.f={Ad:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};u.fa.prototype.e=function(){return u.e("div",{className:"vjs-control-bar"})};u.fa.prototype.aa=function(){u.c.prototype.aa.call(this);this.a.j("controlsvisible")};
u.fa.prototype.ua=function(){u.c.prototype.ua.call(this);this.a.j("controlshidden")};u.Wb=u.o.extend({g:function(a,c){u.o.call(this,a,c);a.d("play",u.bind(this,this.Kb));a.d("pause",u.bind(this,this.Jb))}});t=u.Wb.prototype;t.pa="Play";t.R=function(){return"vjs-play-control "+u.o.prototype.R.call(this)};t.n=function(){this.a.paused()?this.a.play():this.a.pause()};t.Kb=function(){u.w(this.b,"vjs-paused");u.p(this.b,"vjs-playing");this.b.children[0].children[0].innerHTML="Pause"};
t.Jb=function(){u.w(this.b,"vjs-playing");u.p(this.b,"vjs-paused");this.b.children[0].children[0].innerHTML="Play"};u.Za=u.c.extend({g:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.Ca))}});
u.Za.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};
u.Za.prototype.Ca=function(){var a=this.a.Nb?this.a.t.currentTime:this.a.currentTime();this.content.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.La(a,this.a.duration())};u.$a=u.c.extend({g:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.Ca))}});
u.$a.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};u.$a.prototype.Ca=function(){this.a.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Duration Time </span>'+u.La(this.a.duration()))};
u.$b=u.c.extend({g:function(a,c){u.c.call(this,a,c)}});u.$b.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};u.hb=u.c.extend({g:function(a,c){u.c.call(this,a,c);a.d("timeupdate",u.bind(this,this.Ca))}});
u.hb.prototype.e=function(){var a=u.c.prototype.e.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};
u.hb.prototype.Ca=function(){this.a.duration()&&this.a.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.La(this.a.duration()-this.a.currentTime()))};u.Ea=u.o.extend({g:function(a,c){u.o.call(this,a,c)}});u.Ea.prototype.pa="Fullscreen";u.Ea.prototype.R=function(){return"vjs-fullscreen-control "+u.o.prototype.R.call(this)};
u.Ea.prototype.n=function(){this.a.J?(this.a.qb(),this.b.children[0].children[0].innerHTML="Fullscreen"):(this.a.xa(),this.b.children[0].children[0].innerHTML="Non-Fullscreen")};u.gb=u.c.extend({g:function(a,c){u.c.call(this,a,c)}});u.gb.prototype.f={children:{seekBar:{}}};u.gb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-progress-control vjs-control"})};u.Xb=u.N.extend({g:function(a,c){u.N.call(this,a,c);a.d("timeupdate",u.bind(this,this.Ba));a.Q(u.bind(this,this.Ba))}});
t=u.Xb.prototype;t.f={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};t.qc="timeupdate";t.e=function(){return u.N.prototype.e.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};t.Ba=function(){var a=this.a.Nb?this.a.t.currentTime:this.a.currentTime();this.b.setAttribute("aria-valuenow",u.round(100*this.yb(),2));this.b.setAttribute("aria-valuetext",u.La(a,this.a.duration()))};
t.yb=function(){return this.a.currentTime()/this.a.duration()};t.Pa=function(a){u.N.prototype.Pa.call(this,a);this.a.Nb=f;this.pd=!this.a.paused();this.a.pause()};t.Hb=function(a){a=E(this,a)*this.a.duration();a==this.a.duration()&&(a-=0.1);this.a.currentTime(a)};t.Ib=function(a){u.N.prototype.Ib.call(this,a);this.a.Nb=l;this.pd&&this.a.play()};t.wc=function(){this.a.currentTime(this.a.currentTime()+5)};t.vc=function(){this.a.currentTime(this.a.currentTime()-5)};
u.cb=u.c.extend({g:function(a,c){u.c.call(this,a,c);a.d("progress",u.bind(this,this.update))}});u.cb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};u.cb.prototype.update=function(){this.b.style&&(this.b.style.width=u.round(100*this.a.Ia(),2)+"%")};u.Vb=u.c.extend({g:function(a,c){u.c.call(this,a,c)}});
u.Vb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};u.ib=u.ha.extend();u.ib.prototype.defaultValue="00:00";u.ib.prototype.e=function(){return u.ha.prototype.e.call(this,"div",{className:"vjs-seek-handle"})};u.kb=u.c.extend({g:function(a,c){u.c.call(this,a,c);a.h&&(a.h.k&&a.h.k.V===l)&&this.p("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.h.k&&a.h.k.V===l?this.p("vjs-hidden"):this.w("vjs-hidden")}))}});
u.kb.prototype.f={children:{volumeBar:{}}};u.kb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-volume-control vjs-control"})};u.jb=u.N.extend({g:function(a,c){u.N.call(this,a,c);a.d("volumechange",u.bind(this,this.Ba));a.Q(u.bind(this,this.Ba));setTimeout(u.bind(this,this.update),0)}});t=u.jb.prototype;t.Ba=function(){this.b.setAttribute("aria-valuenow",u.round(100*this.a.volume(),2));this.b.setAttribute("aria-valuetext",u.round(100*this.a.volume(),2)+"%")};
t.f={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};t.qc="volumechange";t.e=function(){return u.N.prototype.e.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};t.Hb=function(a){this.a.volume(E(this,a))};t.yb=function(){return this.a.muted()?0:this.a.volume()};t.wc=function(){this.a.volume(this.a.volume()+0.1)};t.vc=function(){this.a.volume(this.a.volume()-0.1)};u.ac=u.c.extend({g:function(a,c){u.c.call(this,a,c)}});
u.ac.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};u.lb=u.ha.extend();u.lb.prototype.defaultValue="00:00";u.lb.prototype.e=function(){return u.ha.prototype.e.call(this,"div",{className:"vjs-volume-handle"})};
u.ga=u.o.extend({g:function(a,c){u.o.call(this,a,c);a.d("volumechange",u.bind(this,this.update));a.h&&(a.h.k&&a.h.k.V===l)&&this.p("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.h.k&&a.h.k.V===l?this.p("vjs-hidden"):this.w("vjs-hidden")}))}});u.ga.prototype.e=function(){return u.o.prototype.e.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};u.ga.prototype.n=function(){this.a.muted(this.a.muted()?l:f)};
u.ga.prototype.update=function(){var a=this.a.volume(),c=3;0===a||this.a.muted()?c=0:0.33>a?c=1:0.67>a&&(c=2);this.a.muted()?"Unmute"!=this.b.children[0].children[0].innerHTML&&(this.b.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.b.children[0].children[0].innerHTML&&(this.b.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.w(this.b,"vjs-vol-"+a);u.p(this.b,"vjs-vol-"+c)};
u.Ga=u.C.extend({g:function(a,c){u.C.call(this,a,c);a.d("volumechange",u.bind(this,this.update));a.h&&(a.h.k&&a.h.k.V===l)&&this.p("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.h.k&&a.h.k.V===l?this.p("vjs-hidden"):this.w("vjs-hidden")}));this.p("vjs-menu-button")}});u.Ga.prototype.Ka=function(){var a=new u.ma(this.a,{Kc:"div"}),c=new u.jb(this.a,u.i.B({od:f},this.f.Dd));a.Z(c);return a};u.Ga.prototype.n=function(){u.ga.prototype.n.call(this);u.C.prototype.n.call(this)};
u.Ga.prototype.e=function(){return u.o.prototype.e.call(this,"div",{className:"vjs-volume-menu-button vjs-menu-button vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};u.Ga.prototype.update=u.ga.prototype.update;u.fb=u.o.extend({g:function(a,c){u.o.call(this,a,c);(!a.poster()||!a.controls())&&this.v();a.d("play",u.bind(this,this.v))}});
u.fb.prototype.e=function(){var a=u.e("div",{className:"vjs-poster",tabIndex:-1}),c=this.a.poster();c&&("backgroundSize"in a.style?a.style.backgroundImage='url("'+c+'")':a.appendChild(u.e("img",{src:c})));return a};u.fb.prototype.n=function(){this.a.play()};
u.Ub=u.c.extend({g:function(a,c){u.c.call(this,a,c);a.d("canplay",u.bind(this,this.v));a.d("canplaythrough",u.bind(this,this.v));a.d("playing",u.bind(this,this.v));a.d("seeked",u.bind(this,this.v));a.d("seeking",u.bind(this,this.show));a.d("seeked",u.bind(this,this.v));a.d("error",u.bind(this,this.show));a.d("waiting",u.bind(this,this.show))}});u.Ub.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-loading-spinner"})};
u.Xa=u.o.extend({g:function(a,c){u.o.call(this,a,c);a.controls()||this.v();a.d("play",u.bind(this,this.v))}});u.Xa.prototype.e=function(){return u.o.prototype.e.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>","aria-label":"play video"})};u.Xa.prototype.n=function(){this.a.play()};u.q=u.c.extend({g:function(a,c,d){u.c.call(this,a,c,d)}});u.q.prototype.n=u.bb?m():function(){this.a.controls()&&(this.a.paused()?this.a.play():this.a.pause())};u.q.prototype.k={V:f,ic:l,Mb:l,Pb:l};
u.media={};u.media.Wa="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function ea(){var a=u.media.Wa[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.Wa.length-1;0<=i;i--)u.q.prototype[u.media.Wa[i]]=ea();
u.m=u.q.extend({g:function(a,c,d){this.k.V=u.m.Jc();this.k.Uc=!u.Tb;this.k.ic=f;u.q.call(this,a,c,d);(c=c.source)&&this.b.currentSrc==c.src?a.j("loadstart"):c&&(this.b.src=c.src);a.Q(function(){this.G&&(this.f.autoplay&&this.paused())&&(delete this.G.poster,this.play())});this.d("click",this.n);for(a=u.m.ab.length-1;0<=a;a--)u.d(this.b,u.m.ab[a],u.bind(this.a,this.Pc));this.Ua()}});t=u.m.prototype;t.F=function(){u.q.prototype.F.call(this)};
t.e=function(){var a=this.a,c=a.G;if(!c||this.k.Uc===l)c?(c.player=h,a.G=h,a.r().removeChild(c),c=c.cloneNode(l)):c=u.e("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,u.zb(c,a.r());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.f[g]!==h&&(c[g]=a.f[g])}return c};t.Pc=function(a){this.j(a);a.stopPropagation()};t.play=function(){this.b.play()};t.pause=function(){this.b.pause()};t.paused=function(){return this.b.paused};t.currentTime=function(){return this.b.currentTime};
t.ed=function(a){try{this.b.currentTime=a}catch(c){u.log(c,"Video is not ready. (Video.js)")}};t.duration=function(){return this.b.duration||0};t.buffered=function(){return this.b.buffered};t.volume=function(){return this.b.volume};t.kd=function(a){this.b.volume=a};t.muted=function(){return this.b.muted};t.hd=function(a){this.b.muted=a};t.width=function(){return this.b.offsetWidth};t.height=function(){return this.b.offsetHeight};
t.Ta=function(){return"function"==typeof this.b.webkitEnterFullScreen&&(/Android/.test(u.H)||!/Chrome|Mac OS X 10.5/.test(u.H))?f:l};t.src=function(a){this.b.src=a};t.load=function(){this.b.load()};t.currentSrc=function(){return this.b.currentSrc};t.Qa=function(){return this.b.Qa};t.jd=function(a){this.b.Qa=a};t.autoplay=function(){return this.b.autoplay};t.dd=function(a){this.b.autoplay=a};t.loop=function(){return this.b.loop};t.gd=function(a){this.b.loop=a};t.error=function(){return this.b.error};
u.m.isSupported=function(){return!!u.na.canPlayType};u.m.ob=function(a){try{return!!u.na.canPlayType(a.type)}catch(c){return""}};u.m.Jc=function(){var a=u.na.volume;u.na.volume=a/2+0.1;return a!==u.na.volume};u.m.ab="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
u.Ec&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});
u.l=u.q.extend({g:function(a,c,d){u.q.call(this,a,c,d);d=c.source;var e=c.parentEl,g=this.b=u.e("div",{id:a.id()+"_temp_flash"}),j=a.id()+"_flash_api";a=a.f;var k=u.i.B({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.Qa,loop:a.loop,muted:a.muted},c.flashVars),q=u.i.B({wmode:"opaque",bgcolor:"#000000"},c.params),n=u.i.B({id:j,name:j,"class":"vjs-tech"},c.attributes);d&&(k.src=encodeURIComponent(u.jc(d.src)));
u.zb(g,e);c.startTime&&this.Q(function(){this.load();this.play();this.currentTime(c.startTime)});if(c.iFrameMode===f&&!u.Ac){var s=u.e("iframe",{id:j+"_iframe",name:j+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});k.readyFunction="ready";k.eventProxyFunction="events";k.errorEventProxyFunction="errors";u.d(s,"load",u.bind(this,function(){var a,d=s.contentWindow;a=s.contentDocument?s.contentDocument:s.contentWindow.document;a.write(u.l.kc(c.swf,k,q,n));d.player=
this.a;d.ready=u.bind(this.a,function(c){c=a.getElementById(c);var d=this.h;d.b=c;u.d(c,"click",d.bind(d.n));u.l.rb(d)});d.events=u.bind(this.a,function(a,c){this&&"flash"===this.za&&this.j(c)});d.errors=u.bind(this.a,function(a,c){u.log("Flash Error",c)})}));g.parentNode.replaceChild(s,g)}else u.l.Oc(c.swf,g,k,q,n)}});t=u.l.prototype;t.F=function(){u.q.prototype.F.call(this)};t.play=function(){this.b.vjs_play()};t.pause=function(){this.b.vjs_pause()};
t.src=function(a){a=u.jc(a);this.b.vjs_src(a);if(this.a.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};t.load=function(){this.b.vjs_load()};t.poster=function(){this.b.vjs_getProperty("poster")};t.buffered=function(){return u.tb(0,this.b.vjs_getProperty("buffered"))};t.Ta=r(l);var P=u.l.prototype,Q="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),R="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");
function fa(){var a=Q[S],c=a.charAt(0).toUpperCase()+a.slice(1);P["set"+c]=function(c){return this.b.vjs_setProperty(a,c)}}function T(a){P[a]=function(){return this.b.vjs_getProperty(a)}}var S;for(S=0;S<Q.length;S++)T(Q[S]),fa();for(S=0;S<R.length;S++)T(R[S]);u.l.isSupported=function(){return 10<=u.l.version()[0]};u.l.ob=function(a){if(a.type in u.l.Rc)return"maybe"};u.l.Rc={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};
u.l.onReady=function(a){a=u.r(a);var c=a.player||a.parentNode.player,d=c.h;a.player=c;d.b=a;d.d("click",d.n);u.l.rb(d)};u.l.rb=function(a){a.r().vjs_getProperty?a.Ua():setTimeout(function(){u.l.rb(a)},50)};u.l.onEvent=function(a,c){u.r(a).player.j(c)};u.l.onError=function(a,c){u.r(a).player.j("error");u.log("Flash Error",c,a)};
u.l.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
u.l.Oc=function(a,c,d,e,g){a=u.l.kc(a,d,e,g);a=u.e("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var j=d.childNodes[0];setTimeout(function(){j.style.display="block"},1E3)};
u.l.kc=function(a,c,d,e){var g="",j="",k="";c&&u.i.sa(c,function(a,c){g+=a+"="+c+"&amp;"});d=u.i.B({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.i.sa(d,function(a,c){j+='<param name="'+a+'" value="'+c+'" />'});e=u.i.B({data:a,width:"100%",height:"100%"},e);u.i.sa(e,function(a,c){k+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+k+">"+j+"</object>"};
u.Fc=u.c.extend({g:function(a,c,d){u.c.call(this,a,c,d);if(!a.f.sources||0===a.f.sources.length){c=0;for(d=a.f.techOrder;c<d.length;c++){var e=u.$(d[c]),g=window.videojs[e];if(g&&g.isSupported()){H(a,e);break}}}else a.src(a.f.sources)}});function U(a){a.Aa=a.Aa||[];return a.Aa}function V(a,c,d){for(var e=a.Aa,g=0,j=e.length,k,q;g<j;g++)k=e[g],k.id()===c?(k.show(),q=k):d&&(k.L()==d&&0<k.mode())&&k.disable();(c=q?q.L():d?d:l)&&a.j(c+"trackchange")}
u.W=u.c.extend({g:function(a,c){u.c.call(this,a,c);this.P=c.id||"vjs_"+c.kind+"_"+c.language+"_"+u.u++;this.uc=c.src;this.Lc=c["default"]||c.dflt;this.md=c.title;this.yd=c.srclang;this.Tc=c.label;this.ia=[];this.bc=[];this.ja=this.ka=0;this.a.d("fullscreenchange",u.bind(this,this.Gc))}});t=u.W.prototype;t.L=p("A");t.src=p("uc");t.ub=p("Lc");t.title=p("md");t.label=p("Tc");t.readyState=p("ka");t.mode=p("ja");t.Gc=function(){this.b.style.fontSize=this.a.J?140*(screen.width/this.a.width())+"%":""};
t.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-"+this.A+" vjs-text-track"})};t.show=function(){W(this);this.ja=2;u.c.prototype.show.call(this)};t.v=function(){W(this);this.ja=1;u.c.prototype.v.call(this)};t.disable=function(){2==this.ja&&this.v();this.a.s("timeupdate",u.bind(this,this.update,this.P));this.a.s("ended",u.bind(this,this.reset,this.P));this.reset();this.a.T.textTrackDisplay.removeChild(this);this.ja=0};
function W(a){0===a.ka&&a.load();0===a.ja&&(a.a.d("timeupdate",u.bind(a,a.update,a.P)),a.a.d("ended",u.bind(a,a.reset,a.P)),("captions"===a.A||"subtitles"===a.A)&&a.a.T.textTrackDisplay.Z(a))}t.load=function(){0===this.ka&&(this.ka=1,u.get(this.uc,u.bind(this,this.ad),u.bind(this,this.Gb)))};t.Gb=function(a){this.error=a;this.ka=3;this.j("error")};
t.ad=function(a){var c,d;a=a.split("\n");for(var e="",g=1,j=a.length;g<j;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(c=e,e=u.trim(a[++g])):c=this.ia.length;c={id:c,index:this.ia.length};d=e.split(" --\x3e ");c.startTime=X(d[0]);c.ta=X(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);c.text=d.join("<br/>");this.ia.push(c)}this.ka=2;this.j("loaded")};
function X(a){var c=a.split(":");a=0;var d,e,g;3==c.length?(d=c[0],e=c[1],c=c[2]):(d=0,e=c[0],c=c[1]);c=c.split(/\s+/);c=c.splice(0,1)[0];c=c.split(/\.|,/);g=parseFloat(c[1]);c=c[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(c);g&&(a+=g/1E3);return a}
t.update=function(){if(0<this.ia.length){var a=this.a.currentTime();if(this.Lb===b||a<this.Lb||this.Ma<=a){var c=this.ia,d=this.a.duration(),e=0,g=l,j=[],k,q,n,s;a>=this.Ma||this.Ma===b?s=this.wb!==b?this.wb:0:(g=f,s=this.Db!==b?this.Db:c.length-1);for(;;){n=c[s];if(n.ta<=a)e=Math.max(e,n.ta),n.Ha&&(n.Ha=l);else if(a<n.startTime){if(d=Math.min(d,n.startTime),n.Ha&&(n.Ha=l),!g)break}else g?(j.splice(0,0,n),q===b&&(q=s),k=s):(j.push(n),k===b&&(k=s),q=s),d=Math.min(d,n.ta),e=Math.max(e,n.startTime),
n.Ha=f;if(g)if(0===s)break;else s--;else if(s===c.length-1)break;else s++}this.bc=j;this.Ma=d;this.Lb=e;this.wb=k;this.Db=q;a=this.bc;c="";d=0;for(e=a.length;d<e;d++)c+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.b.innerHTML=c;this.j("cuechange")}}};t.reset=function(){this.Ma=0;this.Lb=this.a.duration();this.Db=this.wb=0};u.Rb=u.W.extend();u.Rb.prototype.A="captions";u.Yb=u.W.extend();u.Yb.prototype.A="subtitles";u.Sb=u.W.extend();u.Sb.prototype.A="chapters";
u.Zb=u.c.extend({g:function(a,c,d){u.c.call(this,a,c,d);if(a.f.tracks&&0<a.f.tracks.length){c=this.a;a=a.f.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=c,j=e.kind,k=e.label,q=e.language,n=e;e=g.Aa=g.Aa||[];n=n||{};n.kind=j;n.label=k;n.language=q;j=u.$(j||"subtitles");g=new window.videojs[j+"Track"](g,n);e.push(g)}}}});u.Zb.prototype.e=function(){return u.c.prototype.e.call(this,"div",{className:"vjs-text-track-display"})};
u.Y=u.M.extend({g:function(a,c){var d=this.da=c.track;c.label=d.label();c.selected=d.ub();u.M.call(this,a,c);this.a.d(d.L()+"trackchange",u.bind(this,this.update))}});u.Y.prototype.n=function(){u.M.prototype.n.call(this);V(this.a,this.da.P,this.da.L())};u.Y.prototype.update=function(){this.selected(2==this.da.mode())};u.eb=u.Y.extend({g:function(a,c){c.track={L:function(){return c.kind},pc:a,label:function(){return c.kind+" off"},ub:r(l),mode:r(l)};u.Y.call(this,a,c);this.selected(f)}});
u.eb.prototype.n=function(){u.Y.prototype.n.call(this);V(this.a,this.da.P,this.da.L())};u.eb.prototype.update=function(){for(var a=U(this.a),c=0,d=a.length,e,g=f;c<d;c++)e=a[c],e.L()==this.da.L()&&2==e.mode()&&(g=l);this.selected(g)};u.X=u.C.extend({g:function(a,c){u.C.call(this,a,c);1>=this.K.length&&this.v()}});
u.X.prototype.createItems=function(){var a=[],c;a.push(new u.eb(this.a,{kind:this.A}));for(var d=0;d<U(this.a).length;d++)c=U(this.a)[d],c.L()===this.A&&a.push(new u.Y(this.a,{track:c}));return a};u.Da=u.X.extend({g:function(a,c,d){u.X.call(this,a,c,d);this.b.setAttribute("aria-label","Captions Menu")}});u.Da.prototype.A="captions";u.Da.prototype.pa="Captions";u.Da.prototype.className="vjs-captions-button";u.Fa=u.X.extend({g:function(a,c,d){u.X.call(this,a,c,d);this.b.setAttribute("aria-label","Subtitles Menu")}});
u.Fa.prototype.A="subtitles";u.Fa.prototype.pa="Subtitles";u.Fa.prototype.className="vjs-subtitles-button";u.ea=u.X.extend({g:function(a,c,d){u.X.call(this,a,c,d);this.b.setAttribute("aria-label","Chapters Menu")}});u.ea.prototype.A="chapters";u.ea.prototype.pa="Chapters";u.ea.prototype.className="vjs-chapters-button";u.ea.prototype.createItems=function(){for(var a=[],c,d=0;d<U(this.a).length;d++)c=U(this.a)[d],c.L()===this.A&&a.push(new u.Y(this.a,{track:c}));return a};
u.ea.prototype.Ka=function(){for(var a=U(this.a),c=0,d=a.length,e,g,j=this.K=[];c<d;c++)if(e=a[c],e.L()==this.A&&e.ub()){if(2>e.readyState()){this.vd=e;e.d("loaded",u.bind(this,this.Ka));return}g=e;break}a=this.va=new u.ma(this.a);a.b.appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.$(this.A),ld:-1}));if(g){e=g.ia;for(var k,c=0,d=e.length;c<d;c++)k=e[c],k=new u.Ya(this.a,{track:g,cue:k}),j.push(k),a.Z(k)}0<this.K.length&&this.show();return a};
u.Ya=u.M.extend({g:function(a,c){var d=this.da=c.track,e=this.cue=c.cue,g=a.currentTime();c.label=e.text;c.selected=e.startTime<=g&&g<e.ta;u.M.call(this,a,c);d.d("cuechange",u.bind(this,this.update))}});u.Ya.prototype.n=function(){u.M.prototype.n.call(this);this.a.currentTime(this.cue.startTime);this.update(this.cue.startTime)};u.Ya.prototype.update=function(){var a=this.cue,c=this.a.currentTime();this.selected(a.startTime<=c&&c<a.ta)};
u.i.B(u.fa.prototype.f.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)u.JSON=window.JSON;else{u.JSON={};var Y=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,c){function d(a,e){var k,q,n=a[e];if(n&&"object"===typeof n)for(k in n)Object.prototype.hasOwnProperty.call(n,k)&&(q=d(n,k),q!==b?n[k]=q:delete n[k]);return c.call(a,e,n)}var e;a=String(a);Y.lastIndex=0;Y.test(a)&&(a=a.replace(Y,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
u.cc=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),v(c,a)));else{u.mb();break}else u.qd||u.mb()};u.mb=function(){setTimeout(u.cc,1)};u.S(window,"load",function(){u.qd=f});u.mb();u.bd=function(a,c){u.D.prototype[a]=c};var Z=this;Z.rd=f;function $(a,c){var d=a.split("."),e=Z;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};$("videojs",u);$("_V_",u);$("videojs.options",u.options);$("videojs.players",u.wa);$("videojs.cache",u.qa);$("videojs.Component",u.c);u.c.prototype.player=u.c.prototype.pc;u.c.prototype.dispose=u.c.prototype.F;u.c.prototype.createEl=u.c.prototype.e;u.c.prototype.el=u.c.prototype.r;u.c.prototype.addChild=u.c.prototype.Z;u.c.prototype.children=u.c.prototype.children;u.c.prototype.on=u.c.prototype.d;u.c.prototype.off=u.c.prototype.s;u.c.prototype.one=u.c.prototype.S;u.c.prototype.trigger=u.c.prototype.j;
u.c.prototype.triggerReady=u.c.prototype.Ua;u.c.prototype.show=u.c.prototype.show;u.c.prototype.hide=u.c.prototype.v;u.c.prototype.width=u.c.prototype.width;u.c.prototype.height=u.c.prototype.height;u.c.prototype.dimensions=u.c.prototype.Mc;u.c.prototype.ready=u.c.prototype.Q;u.c.prototype.fadeIn=u.c.prototype.aa;u.c.prototype.fadeOut=u.c.prototype.ua;$("videojs.Player",u.D);u.D.prototype.dispose=u.D.prototype.F;u.D.prototype.requestFullScreen=u.D.prototype.xa;u.D.prototype.cancelFullScreen=u.D.prototype.qb;
u.D.prototype.bufferedPercent=u.D.prototype.Ia;$("videojs.MediaLoader",u.Fc);$("videojs.TextTrackDisplay",u.Zb);$("videojs.ControlBar",u.fa);$("videojs.Button",u.o);$("videojs.PlayToggle",u.Wb);$("videojs.FullscreenToggle",u.Ea);$("videojs.BigPlayButton",u.Xa);$("videojs.LoadingSpinner",u.Ub);$("videojs.CurrentTimeDisplay",u.Za);$("videojs.DurationDisplay",u.$a);$("videojs.TimeDivider",u.$b);$("videojs.RemainingTimeDisplay",u.hb);$("videojs.Slider",u.N);$("videojs.ProgressControl",u.gb);
$("videojs.SeekBar",u.Xb);$("videojs.LoadProgressBar",u.cb);$("videojs.PlayProgressBar",u.Vb);$("videojs.SeekHandle",u.ib);$("videojs.VolumeControl",u.kb);$("videojs.VolumeBar",u.jb);$("videojs.VolumeLevel",u.ac);$("videojs.VolumeHandle",u.lb);$("videojs.MuteToggle",u.ga);$("videojs.PosterImage",u.fb);$("videojs.Menu",u.ma);$("videojs.MenuItem",u.M);$("videojs.MenuButton",u.C);u.C.prototype.createItems=u.C.prototype.wd;$("videojs.SubtitlesButton",u.Fa);$("videojs.CaptionsButton",u.Da);
$("videojs.ChaptersButton",u.ea);$("videojs.MediaTechController",u.q);u.q.prototype.features=u.q.prototype.k;u.q.prototype.k.volumeControl=u.q.prototype.k.V;u.q.prototype.k.fullscreenResize=u.q.prototype.k.ic;u.q.prototype.k.progressEvents=u.q.prototype.k.Mb;u.q.prototype.k.timeupdateEvents=u.q.prototype.k.Pb;$("videojs.Html5",u.m);u.m.Events=u.m.ab;u.m.isSupported=u.m.isSupported;u.m.canPlaySource=u.m.ob;u.m.prototype.setCurrentTime=u.m.prototype.ed;u.m.prototype.setVolume=u.m.prototype.kd;
u.m.prototype.setMuted=u.m.prototype.hd;u.m.prototype.setPreload=u.m.prototype.jd;u.m.prototype.setAutoplay=u.m.prototype.dd;u.m.prototype.setLoop=u.m.prototype.gd;$("videojs.Flash",u.l);u.l.isSupported=u.l.isSupported;u.l.canPlaySource=u.l.ob;u.l.onReady=u.l.onReady;$("videojs.TextTrack",u.W);u.W.prototype.label=u.W.prototype.label;$("videojs.CaptionsTrack",u.Rb);$("videojs.SubtitlesTrack",u.Yb);$("videojs.ChaptersTrack",u.Sb);$("videojs.autoSetup",u.cc);$("videojs.plugin",u.bd);
$("videojs.createTimeRange",u.tb);})();//@ sourceMappingURL=video.js.map
